# Generated by Django 4.2.4 on 2023-09-17 02:51

import conf.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('pais', models.IntegerField(choices=[(1, 'URUGUAY'), (2, 'ARGENTINA'), (3, 'CHILE')], default=1)),
                ('fecha_fundado', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.FloatField(blank=True, null=True, validators=[conf.validators.CustomValidators.valor_no_negativo])),
                ('pie', models.IntegerField(choices=[(1, 'DERECHO'), (2, 'IZQUIERDO')])),
                ('fichado', models.DateField(blank=True, null=True)),
                ('fin_contrato', models.DateField(blank=True, null=True)),
                ('posicion', models.IntegerField(choices=[(1, 'ARQUERO'), (2, 'LATERAL IZQUIERDO'), (3, 'LATERAL DERECHO'), (2, 'LATERAL IZQUIERDO'), (4, 'MEDIOCAMPO'), (5, 'VOLANTE IZQUIERDO'), (6, 'VOLANTE DERECHA'), (7, 'DELANTERO'), (8, 'DEFENSA CENTRAL'), (9, 'SIN DEFINIR')], default=9)),
                ('salario', models.FloatField(default=0, validators=[conf.validators.CustomValidators.valor_no_negativo])),
                ('valor_mercado', models.FloatField(default=0, validators=[conf.validators.CustomValidators.valor_no_negativo])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellido'],
                'permissions': (('ver_salario', 'Permite a los dirigentes ver el salario'),),
            },
        ),
        migrations.CreateModel(
            name='EquipoTrofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trofeo', models.IntegerField(choices=[(1, 'CAMPEONATO URUGUAYO'), (3, 'COPA LIBERTADORES'), (2, 'INTERMEDIO'), (4, 'COPA INTERCONTINENTAL')])),
                ('cantidad', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'verbose_name_plural': 'trofeo',
                'ordering': ['trofeo'],
                'unique_together': {('equipo', 'trofeo')},
            },
        ),
    ]
