# Generated by Django 4.2.4 on 2023-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
