# Generated by Django 4.2.4 on 2023-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_alter_jugador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='pie',
            field=models.IntegerField(blank=True, choices=[(1, 'DERECHO'), (2, 'IZQUIERDO')], null=True),
        ),
    ]
