# Generated by Django 4.2.4 on 2023-11-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0004_alter_jugador_pie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='pie',
            field=models.IntegerField(blank=True, choices=[(1, 'DERECHO'), (2, 'IZQUIERDO'), (3, 'SIN DEFINIR')], null=True),
        ),
    ]
