# Generated by Django 4.2.4 on 2023-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_alter_jugador_pie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='equipotrofeo',
            name='trofeo',
            field=models.IntegerField(choices=[(1, 'Campeonato uruguayo'), (3, 'Copa Libertadores'), (2, 'Intermedio'), (4, 'Copa Intercontinental')]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.IntegerField(choices=[(1, 'Arquero'), (2, 'Lateral izquierdo'), (3, 'Lateral derecho'), (2, 'Lateral izquierdo'), (4, 'Mediocampo'), (5, 'Volante izquierdo'), (6, 'Volante derecho'), (7, 'Delantero'), (8, 'Defensa central'), (9, 'Sin definir')], default=9),
        ),
    ]
