"""
Django settings for vulnerable project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib import messages
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


LOGIN_REDIRECT_URL = '/demo/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/'
AUTH_USER_MODEL = 'perfil.Perfil'


# Initialise environment variables
env = environ.Env()
environ.Env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = env('MY_SECRET_KEY')
RECAPTCHA_PUBLIC_KEY  = env('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_PRIVATE_KEY')
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

USE_I18N = True


# Application definition

LOCAL_APPS = [
    'conf.apps.ConfConfig',
    'demo.apps.DemoConfig',
    'usuario.apps.UsuarioConfig',
    'equipo.apps.EquipoConfig',
    'campeonato.apps.CampeonatoConfig',

    ]

DJANGO_APPS = [
    'perfil.apps.PerfilConfig',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
]

THIRD_PARTY_APPS = [
    'polymorphic',
    'axes',
    'captcha',
]


INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    #'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesStandaloneBackend',
    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]



ROOT_URLCONF = 'novulnerable.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'novulnerable.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.mysql',
        "NAME": "novulnerable",
        "USER": "root",
        "PASSWORD": "admin",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}


FIXTURE_DIRS = [
    "equipo.fixtures",
]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_HOST = env('EMAIL_HOST')#'smtp.googlemail.com'
EMAIL_PORT = env('EMAIL_PORT')#587
EMAIL_HOST_USER = env('EMAIL_HOST_USER')#'proyectoprogsd@gmail.com'
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

EMAIL_USE_TLS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Auto logout
AUTO_LOGOUT = {
    'IDLE_TIME': 1800, # 600 segundos son 10 minutos
    #'SESSION_TIME': timedelta(minutes=30),
    'MESSAGE': 'Sesión finalizada, por favor haga login de nuevo.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}


# axes configuration settings
# python manage.py axes_reset
AXES_FAILURE_LIMIT: 5 # cantidad de intentos fallidos
AXES_COOLOFF_TIME: 1 # Tiempo de espera para poder loguear de nuevo (es en horas) 
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = 'registration/cuenta_bloqueada.html'


EXTENSIONES_PERMITIDAS_PARA_IMAGENES = ['.jpg', '.jpeg', '.png', ]
MAXIMO_PERMITIDO_MB_IMAGENES = 5 * 1024 * 1024   # 2 mb
MAXIMO_PERMITIDO_MB_ARCHIVO =  5 * 1024 * 1024   # 5 mb

SECURE_SSL_REDIRECT=False
SESSION_COOKIE_SECURE=False
CSRF_COOKIE_SECURE=False



# # Content Security Policy
#
# CSP_IMG_SRC = ("'self'")
#
# CSP_STYLE_SRC = ("'self'")
#
# CSP_SCRIPT_SRC = ("'self'")